[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/points"
  to = "/.netlify/functions/points"
  status = 200
